name: Daily Commit Workflow

on:
  schedule:
    # Runs once daily at 12:00 UTC
    - cron: "0 12 * * *"  # Customize this time to match your required time
  workflow_dispatch: # Allow manual triggers

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add a commit - snehapriya.voruganti@gramener.com
        run: |
          echo "Automated commit on $(date +'%Y-%m-%d %H:%M:%S')" >> daily_commit.log
          git config --global user.name "GitHub Actions"
          git config --global user.email "kethu.seshasarathreddy@gramener.com"
          git add daily_commit.log
          git commit -m "chore: daily automated commit"
          git push origin main

      - name: Debug Git Status
        run: git status
